Use React and Redux
Graycemuthui/Football-Standings pull request #4
Opened 2022-07-27 14:03 UTC by Graycemuthui

### Description
In this project I achieved the following:
- Created Routes for both the HomePage and the Details Page
- Used Redux
- Styled the components
- Tested all components
- Used proper Gitflow

2022-07-27 14:29 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Graycemuthui,

Good job so far!
✔️ App is properly deployed
✔️ Tests are passing
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 14:29 UTC, TedLivist commented on README.md
> +- Details Backgroung by Martí Pardo from [pexels](https://www.pexels.com/photo/group-of-men-playing-soccer-1657328/)
- [ ] Kindly include acknowledgment for Nelson Sakwa, the designerr.

2022-07-27 14:29 UTC, TedLivist commented on src/components/HomePage.js
> +  );
- [ ] Your homepage is expected to contain a filtering mechanism, like a search box or something that allows users to filter the contents on the homepage. Kindly ensure your implement that.

  ![furkan-home](https://user-images.githubusercontent.com/36542986/181271738-a961f4b1-8dce-4f0e-833a-0d87f88e8877.jpg)

2022-07-27 14:29 UTC, TedLivist commented on src/components/HomePage.js
> +        </p>
- [ ] In keeping with the design I think this text should be moved away from the right side of the page and more toward the center of the half container to make it legible.

  ![grace-muthui-right](https://user-images.githubusercontent.com/36542986/181273202-588c05fa-db9c-459e-bc84-7dca0acee1d6.jpg)

2022-07-28 13:30 UTC, rloterh commented on src/components/HomePage.js
> +  );
This issue is well resolved! ✔️

2022-07-28 13:30 UTC, rloterh commented on src/components/HomePage.js
> +        </p>
This issue is well resolved! ✔️

2022-07-28 13:34 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Geegee,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- React Router properly implemented
- State management properly implemented
- Integration test properly implemented
- Good ReadMe
- Clean code
- Nice UI design

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 14:07 UTC, Graycemuthui commented
Thank you

2022-07-28 14:07 UTC, merged